package flow

import (
	"os"
	"path/filepath"
	"testing"
)

// A vendored pipeline has no local code and no card. In `github` mode the delivery used to
// look the unit's code up in the map and refuse — measured in blue-eyes on
// `anchors-claim.yml`. It must now succeed without demanding a code, and without falling
// back to `changes/`, which is the local mode's mechanism.
func TestDeliver_upstreamPipelineDemandsNoCode(t *testing.T) {
	root := t.TempDir()
	write := func(rel, body string) {
		t.Helper()
		p := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("anchors.yaml", "version: 2\nworkflow:\n  mode: github\n  repo: acme/app\n  labels: [anchors]\n"+
		"layers:\n  workflow:\n    pattern: \".github/workflows/*.yml\"\n    kind: code\n")
	unit := ".github/workflows/anchors-claim.yml"
	write(unit, "# anchors:template — generated by anchors.\non: push\n")

	cmd := newDeliverCmd()
	cmd.SetArgs([]string{"--root", root, "--stage", "code", "--unit", filepath.Join(root, unit),
		"--intent", "doctor --fix refreshed the pipeline", "--date", "2026-09-23"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("an upstream-owned pipeline must not demand a local code: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, "changes")); err == nil {
		t.Error("in github mode the record must not fall back to changes/")
	}
}
