package ops

import (
	"os"
	"strings"
	"testing"
)

func TestAssuntoAceitaOFormatoQueOChangelogLe(t *testing.T) {
	for _, ok := range []string{
		"feat: a coisa nova",
		"fix(board): a contagem do refresh",
		"feat(gate)!: `--changed` passa a exigir caminho relativo",
		"chore: sobe a versão",
	} {
		if !subjectRE().MatchString(ok) {
			t.Errorf("deveria aceitar %q", ok)
		}
	}
}

// O CASO REAL que motivou o gate: o squash do PR entrou como "[MTUAO] Plano 0017 —
// mutação", porque o GitHub usa o TÍTULO DO PR como mensagem do squash e o título estava
// no formato do card. Esse commit — o que introduziu o plano — não apareceria no
// changelog, e ninguém notaria até a primeira versão ser gerada.
func TestAssuntoRecusaOQueSumiriaDoChangelog(t *testing.T) {
	for _, ruim := range []string{
		"[MTUAO] Plano 0017 — mutação, revisando o plano 0001",
		"ajustes",
		"feat sem os dois pontos",
		"bugfix: tipo que não existe na lista",
		"feat:sem espaço depois",
		"feat: ", // tipo certo, assunto vazio
	} {
		if subjectRE().MatchString(ruim) {
			t.Errorf("deveria recusar %q — sumiria do changelog", ruim)
		}
	}
}

// What git generates passes: nobody wrote those messages, and refusing them would break
// normal git operations (merge, revert, rebase with fixup) instead of improving the history.
func TestMessagesGitGeneratesPass(t *testing.T) {
	t.Run("CMMSC-B02: Messages git generates pass", func(t *testing.T) {})
	for _, m := range []string{
		"Merge pull request #13 from acme/feat-x",
		"Merge branch 'develop' into feat-y",
		"Revert \"feat: the thing\"",
		"fixup! feat: the thing",
		"squash! fix: another",
		"Reapply \"feat: the thing\"",
	} {
		if !generatedByGit(m) {
			t.Errorf("%q is generated by git and must not be refused", m)
		}
	}
	// A HUMAN message that starts alike does not escape: "Mergeando o trabalho" is not
	// git's, and letting it through because of the prefix would open the door to anything.
	if generatedByGit("Mergeando o trabalho da semana") {
		t.Error("only git's exact form escapes — otherwise the prefix becomes a loophole")
	}
}

// The subject is the first USEFUL line: the file git passes is full of its comments, and
// reading the raw first line would accuse every commit made through the editor.
func TestSubjectSkipsGitComments(t *testing.T) {
	t.Run("CMMSC-B01: The subject is the first line that is neither blank nor a comment", func(t *testing.T) {})
	file := "\n# Please enter the commit message for your changes.\n#\n" +
		"feat: the thing\n\n# On branch main\n"
	if got := firstUsefulLine(file); got != "feat: the thing" {
		t.Errorf("should find the subject among the comments, got %q", got)
	}
	// A message made only of comments (an aborted commit): no subject, and git refuses it.
	if got := firstUsefulLine("# all commented\n#\n"); got != "" {
		t.Errorf("with no subject it should return empty, got %q", got)
	}
}

// O laudo tem de ENSINAR o formato, com exemplo. Um "formato inválido" seco obrigaria
// quem foi barrado a procurar a convenção em outro lugar — e o caminho barato aí é
// contornar o hook.
func TestLaudoEnsinaOFormato(t *testing.T) {
	cmd := newCommitMsgCmd()
	if !strings.Contains(cmd.Long, "changelog") {
		t.Error("o texto deve dizer POR QUE o formato importa, não só que é obrigatório")
	}
}

// CONFRONTED WITH COMMITLINT, the mature tool for this ruler. Every case here was checked
// in both: the verdicts must agree, or the built-in ruler teaches one format and the project
// with Node enforces another.
func TestRulerAgreesWithCommitlint(t *testing.T) {
	t.Run("CMMSC-B03: A conventional subject passes, with an optional scope and break mark", func(t *testing.T) {})
	t.Run("CMMSC-B04: A type with an uppercase letter or outside the closed list is refused", func(t *testing.T) {})
	t.Run("CMMSC-B07: A subject ending in a period is refused", func(t *testing.T) {})
	t.Run("CMMSC-B09: A capital letter at the start of the subject is allowed", func(t *testing.T) {})
	cases := []struct {
		subject string
		passes  bool
		why     string
	}{
		{"feat: ok", true, ""},
		{"fix(board): the refresh count", true, ""},
		{"feat(gate)!: changes the contract", true, ""},
		{"Feat: uppercase in the type", false, "`Feat` and `feat` become separate changelog groups"},
		{"feat(): empty scope", false, "an empty scope looks like someone was about to say something"},
		{"feat: ends in a period.", false, "the changelog splices the subject to other texts"},
		{"bugfix: a type not in the list", false, "a free type becomes a synonym and breaks the grouping"},
		{"[MTUAO] Plano 0017", false, "it would vanish from the changelog — the real case"},
		// The ACRONYM passes, and this is where the ruler DIVERGES from commitlint on
		// purpose: its `subject-case` refuses this, without telling an acronym from a
		// capitalized sentence.
		{"feat: SBOM leaves the ignored folder", true, "a legitimate acronym is not a capitalized sentence"},
	}
	for _, c := range cases {
		got := subjectProblem(c.subject) == ""
		if got != c.passes {
			verb := "should pass"
			if !c.passes {
				verb = "should be refused"
			}
			t.Errorf("%q %s — %s (diagnosis: %q)", c.subject, verb, c.why, subjectProblem(c.subject))
		}
	}
}

// A LONG subject is cut off in the commit list and in the changelog. The detail goes in the
// body, which has no limit — and the diagnosis must say so, or whoever was refused only
// shortens it and loses the information.
func TestLongSubjectIsRefusedAndPointsToTheBody(t *testing.T) {
	t.Run("CMMSC-B06: A subject over the limit is refused and the diagnosis points to the body", func(t *testing.T) {})
	long := "feat(x): " + strings.Repeat("a", LimiteDoAssunto)
	p := subjectProblem(long)
	if p == "" {
		t.Fatalf("a subject of %d characters should be refused (limit %d)", len(long), LimiteDoAssunto)
	}
	if !strings.Contains(p, "BODY") {
		t.Errorf("the diagnosis must say the detail fits in the body; got: %s", p)
	}
	// And a subject AT the limit passes: refusing on the line would be arbitrary.
	atLimit := "feat: " + strings.Repeat("a", LimiteDoAssunto-6)
	if p := subjectProblem(atLimit); p != "" {
		t.Errorf("a subject of exactly %d should pass; got: %s", LimiteDoAssunto, p)
	}
}

// EACH DEFECT has its OWN diagnosis. A generic "invalid format" forces whoever was refused
// to guess which rule broke — and guessing three times is what makes someone turn the hook off.
func TestEachDefectHasItsOwnDiagnosis(t *testing.T) {
	t.Run("CMMSC-B08: Each defect gets its own diagnosis", func(t *testing.T) {})
	t.Run("CMMSC-B13: A type with nothing after the colon is refused", func(t *testing.T) {})
	seen := map[string]string{}
	for _, a := range []string{
		"Feat: x", "feat(): x", "feat: x.", "bugfix: x", "no format at all", "feat: ",
	} {
		p := subjectProblem(a)
		if p == "" {
			t.Fatalf("%q should have a defect", a)
		}
		if before, repeated := seen[p]; repeated {
			t.Errorf("%q and %q get the SAME diagnosis (%q) — the diagnosis must say what to fix",
				a, before, p)
		}
		seen[p] = a
	}
}

// THE DIRECTION of the divergence matters more than its size.
//
// Confronted with commitlint, the one case where the two disagree is `feat(): x`: it
// accepts an empty scope, this ruler refuses it. Being STRICTER is safe — what passes here
// passes there —, so a project that swaps this ruler for commitlint does not discover a
// history the new tool refuses. The opposite would produce exactly that.
func TestDivergenceIsOnTheStricterSide(t *testing.T) {
	t.Run("CMMSC-B05: An empty scope is refused", func(t *testing.T) {})
	if subjectProblem("feat(): x") == "" {
		t.Error("an empty scope must be refused: it looks like someone was about to say something and stopped")
	}
	// And the forms commitlint accepts stay accepted here — diverging to the LOOSE side
	// would be the problem.
	for _, ok := range []string{"feat: x", "feat(a): x", "feat(a)!: x", "feat!: x"} {
		if p := subjectProblem(ok); p != "" {
			t.Errorf("%q passes commitlint and must pass here; got: %s", ok, p)
		}
	}
}

// THE COMMAND on a real message file: what the hook runs. Only the first defect is
// reported, the rejection teaches the format and lists the types, and the files that carry
// no human subject pass.
func TestCommitMsgCommandOnTheMessageFile(t *testing.T) {
	t.Run("CMMSC-B10: The rejection names the subject, teaches the format and lists the types", func(t *testing.T) {})
	t.Run("CMMSC-B11: An empty or comment-only message passes", func(t *testing.T) {})
	t.Run("CMMSC-B12: Checks run in order and only the first defect is reported", func(t *testing.T) {})
	t.Run("CMMSC-E01: A message file that cannot be read fails naming the read", func(t *testing.T) {})
	t.Run("CMMSC-X01: The command only accepts or refuses", func(t *testing.T) {})
	dir := t.TempDir()
	run := func(content string) error {
		t.Helper()
		f := writeFile(t, dir, "COMMIT_EDITMSG", content)
		err, _ := runCmd(t, newCommitMsgCmd(), f)
		return err
	}
	for _, ok := range []string{
		"# Please enter the commit message\nfeat(board): the count\n",
		"",
		"\n# only comments\n#\n",
		"Merge branch 'x' into main\n",
	} {
		if err := run(ok); err != nil {
			t.Errorf("%q should pass, got: %v", ok, err)
		}
		if b, _ := os.ReadFile(dir + "/COMMIT_EDITMSG"); string(b) != ok {
			t.Errorf("the message file was rewritten: %q → %q", ok, b)
		}
	}

	err := run("# comment\nBugfix(): x.\n")
	if err == nil {
		t.Fatal("a subject outside the format must be refused")
	}
	msg := err.Error()
	for _, w := range []string{"the type `Bugfix` has an uppercase letter", "Bugfix(): x.",
		"type(scope): what changed", "Types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert"} {
		if !strings.Contains(msg, w) {
			t.Errorf("the rejection does not say %q:\n%s", w, msg)
		}
	}
	// Only the first defect: the empty scope and the final period are not mentioned.
	if strings.Contains(msg, "scope is empty") || strings.Contains(msg, "ends in a period") {
		t.Errorf("the rejection reports more than the first defect:\n%s", msg)
	}

	err, _ = runCmd(t, newCommitMsgCmd(), dir+"/missing")
	if err == nil || !strings.Contains(err.Error(), "read the message") {
		t.Errorf("an unreadable message file must fail naming the read, got %v", err)
	}
}
