// @anchors
//   code: NTTNW
//   ref: NWTMN

package ops

import (
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"testing"

	"github.com/co2-lab/anchors/internal/config"
)

// The catalog LETTERS and the engine's CANONICAL letters are two halves of the same
// decision, and they diverged with nothing to flag it: the catalog declared `invariants`
// with `I` and `errors` with `E`, and neither was in DefaultRuleLetters.
//
// The effect was the framework emitting a spec it refuses itself — choosing Invariants in
// `anchors new` was enough for a rule to be born invisible to traceability.
//
// This test stops the regression: changing one list without the other fails here, not in
// a user's spec months later.
func TestCatalogUsesOnlyCanonicalLetters(t *testing.T) {
	t.Run("NWTMN-B05: Every section realizes only canonical rule letters", func(t *testing.T) {})
	canonical := map[rune]bool{}
	for _, l := range config.DefaultRuleLetters {
		canonical[l] = true
	}
	seen := map[string]bool{}
	for _, tpl := range templates {
		for _, s := range tpl.sections {
			if s.Realizes == "" || seen[s.Realizes] {
				continue
			}
			seen[s.Realizes] = true
			for _, l := range s.Realizes {
				if !canonical[l] {
					t.Errorf("section %q realizes the letter %q, which is not canonical (%s) — a spec "+
						"generated by `anchors new` would be born with a rule invisible to traceability",
						s.Key, s.Realizes, config.DefaultRuleLetters)
				}
			}
		}
	}
	if len(seen) == 0 {
		t.Fatal("no section with Realizes found — the test confronted nothing")
	}
}

// Every kind of the catalog is born through `anchors new`, each at the given path.
func TestCatalogKindsAreAllBornByNew(t *testing.T) {
	t.Run("NWTMN-B01: The catalog holds seven kinds and each is born by new", func(t *testing.T) {})
	var kinds []string
	for k := range templates {
		kinds = append(kinds, k)
	}
	sort.Strings(kinds)
	if got := strings.Join(kinds, ","); got != "action,feature,flow,plan,product,spec,test" {
		t.Fatalf("kinds = %s", got)
	}
	root := t.TempDir()
	for _, k := range kinds {
		out := filepath.Join("u", "Unit"+templates[k].ext)
		if k == "test" {
			out = filepath.Join("u", "unit_test.go")
		}
		if err, msg := runNew(t, k, "Unit"+k, "--root", root, "--out", filepath.Join(k, out), "--code", "ABCDE"); err != nil {
			t.Errorf("new %s: %v\n%s", k, err, msg)
			continue
		}
		if b, _ := os.ReadFile(filepath.Join(root, k, out)); !strings.Contains(string(b), "ABCDE") {
			t.Errorf("new %s wrote no identity:\n%s", k, b)
		}
	}
}

// Each artifact's header speaks the comment dialect of its file.
func TestHeaderDialectsFollowTheArtifact(t *testing.T) {
	t.Run("NWTMN-B02: A markdown header is an HTML comment with the identity and placeholders", func(t *testing.T) {})
	t.Run("NWTMN-B03: A feature header opens with the Gherkin language line", func(t *testing.T) {})
	t.Run("NWTMN-B04: A test header uses the line comment of the output file", func(t *testing.T) {})
	if got := specTemplate.headerFn("ABCDE", "a/X.spec.md"); got != "<!-- @anchors\n  code: ABCDE\n  updated_at: TODO\n  layer: TODO\n-->\n" {
		t.Errorf("spec header = %q", got)
	}
	if got := featureHeader("ABCDE", ""); !strings.HasPrefix(got, "# language: en\n# @anchors\n#   ref: ABCDE\n") ||
		!strings.Contains(got, "#   layer: feature\n") {
		t.Errorf("feature header without a language = %q", got)
	}
	if got := featureHeader("ABCDE", "pt"); !strings.HasPrefix(got, "# language: pt\n") {
		t.Errorf("feature header in pt = %q", got)
	}
	for out, prefix := range map[string]string{
		"a/calc_test.py": "# @anchors\n#   ref: ABCDE\n",
		"a/calc.test.ts": "// @anchors\n//   ref: ABCDE\n",
		"a/calc_test.go": "// @anchors\n//   ref: ABCDE\n",
	} {
		if got := testTemplate.headerFn("ABCDE", out); !strings.HasPrefix(got, prefix) || !strings.Contains(got, "layer: test") {
			t.Errorf("test header for %s = %q, want the prefix %q", out, got, prefix)
		}
	}
}

// The spec presets: the named unit kinds, each a set of catalog sections in reading
// order, opening with the title and closing with the open decisions.
func TestSpecPresetsAreOrderedSectionSets(t *testing.T) {
	t.Run("NWTMN-B09: Each spec preset is an ordered set of catalog sections", func(t *testing.T) {})
	var names []string
	for n := range specPresets {
		names = append(names, n)
	}
	sort.Strings(names)
	want := "api,backend-logic,component,handler,hook,mobile-logic,repository,schema,screen,service,store,validation"
	if got := strings.Join(names, ","); got != want {
		t.Errorf("presets = %s, want %s", got, want)
	}
	known := map[string]bool{}
	for _, s := range specTemplate.sections {
		known[s.Key] = true
	}
	for n, p := range specPresets {
		for _, k := range p.Sections {
			if !known[k] {
				t.Errorf("preset %s names the unknown section %q", n, k)
			}
		}
		if p.Sections[0] != "title" || p.Sections[len(p.Sections)-1] != "open" {
			t.Errorf("preset %s does not open with title and close with open: %v", n, p.Sections)
		}
	}
}

// Product doctrine does NOT inherit the spec's body.
//
// `sectionBody` resolves the body through `section.body.<key>` in the translation
// catalog, and the template's literal only counts when the key is absent there. With bare
// keys (`rules`, `overview`) the doctrine silently inherited the SPEC's text — measured:
// the command emitted `### XXXXX-B01 — TODO rule` and "what the unit does", spec text in
// an artifact that has no unit at all.
func TestNewProduct_doesNotInheritTheSpecBody(t *testing.T) {
	t.Run("NWTMN-B10: Product doctrine has its own sections and no layer", func(t *testing.T) {})
	tpl, ok := templates["product"]
	if !ok {
		t.Fatal("the `product` kind is not registered")
	}
	for _, s := range tpl.sections {
		if !strings.HasPrefix(s.Key, "doctrine_") {
			t.Errorf("section %q without the `doctrine_` prefix: it will inherit another kind's body", s.Key)
		}
	}
	body := renderArtifact(tpl, "CreditLimit", "CRLMT", "product/x.doctrine.md", t.TempDir(),
		map[string]bool{"doctrine_title": true, "doctrine_rules": true}, nil, nil)
	if !strings.Contains(body, "CRLMT-R01") {
		t.Errorf("the doctrine should emit `-R01` rules, got:\n%s", body)
	}
	if strings.Contains(body, "-B01 — TODO rule") {
		t.Errorf("the doctrine inherited the spec body:\n%s", body)
	}
	// Doctrine has no TARGET: the layer belongs to the target a spec describes, and a
	// `layer: TODO` here would be a field nobody can fill — the eternal placeholder that
	// `placeholder-filled` exists to accuse.
	if strings.Contains(tpl.headerFn("CRLMT", "product/x.doctrine.md"), "layer:") {
		t.Error("the doctrine header must not declare `layer:`")
	}
}

// The test skeleton is BORN in the project's language. Before, `anchors new test` emitted
// `describe/it` with a `//` comment for every stack — a `.py` with JavaScript inside,
// invalid syntax, a file that does not run. And it contradicted `anchors init`, which
// offers 18 stacks.
func TestTestBodyPerFamily(t *testing.T) {
	t.Run("NWTMN-B06: The test body is idiomatic for each known family", func(t *testing.T) {})
	cases := []struct {
		family string
		// must contain: the language's idiomatic construct
		has []string
		// must not contain: ANOTHER language's syntax
		hasNot []string
	}{
		{"python", []string{"def test_calc_total(", "[XXXXX-B01]"}, []string{"describe(", "=>", "//"}},
		{"go", []string{"func TestCalcTotal(t *testing.T)", "[XXXXX-B01]"}, []string{"describe(", "=>", "def "}},
		{"java", []string{"@Test", "void calcTotal()", "[XXXXX-B01]"}, []string{"describe(", "def "}},
		{"kotlin", []string{"@Test", "[XXXXX-B01]"}, []string{"describe(", "def "}},
		{"csharp", []string{"[Fact]", "public void CalcTotal()"}, []string{"describe(", "def "}},
		{"rust", []string{"#[test]", "fn calc_total()"}, []string{"describe(", "def "}},
		{"ruby", []string{"describe '", "do", "end"}, []string{"=>", "def test_"}},
		{"php", []string{"public function testCalcTotal(): void"}, []string{"describe(", "def "}},
		{"ts", []string{"describe(", "it(", "=>"}, []string{"def ", "@Test"}},
	}
	for _, c := range cases {
		t.Run(c.family, func(t *testing.T) {
			got := testBody(c.family, "calcTotal", "XXXXX")
			for _, want := range c.has {
				if !strings.Contains(got, want) {
					t.Errorf("does not contain %q:\n%s", want, got)
				}
			}
			for _, forbidden := range c.hasNot {
				if strings.Contains(got, forbidden) {
					t.Errorf("another language's syntax leaked (%q):\n%s", forbidden, got)
				}
			}
		})
	}
}

// The scenario code in the case NAME is what `anchors ingest --junit` crosses with the
// spec — without it, the scenario-coverage gate never learns the requirement has a green
// test. It is the UNIVERSAL part of the skeleton and cannot be missing in any family.
func TestTestBodyAlwaysCarriesTheScenarioCode(t *testing.T) {
	t.Run("NWTMN-B07: Every test body carries the scenario code", func(t *testing.T) {})
	for _, f := range []string{"python", "go", "java", "kotlin", "csharp", "rust", "ruby", "php", "ts", "", "elixir-we-do-not-know"} {
		t.Run("family="+f, func(t *testing.T) {
			if got := testBody(f, "something", "ABCDX"); !strings.Contains(got, "ABCDX-B01") {
				t.Fatalf("skeleton without the scenario code — the test is born orphaned of the requirement:\n%s", got)
			}
		})
	}
}

// A declared family we do not know: better an INSTRUCTION than a syntax guess. Emitting
// `describe/it` as a "default" is exactly the bias being corrected.
func TestTestBodyUnknownFamilyDoesNotGuess(t *testing.T) {
	t.Run("NWTMN-B08: An unknown family gets an instruction, not guessed syntax", func(t *testing.T) {})
	got := testBody("cobol", "something", "ABCDX")
	if strings.Contains(got, "describe(") || strings.Contains(got, "def ") {
		t.Fatalf("guessed a syntax for an unknown family:\n%s", got)
	}
	if !strings.Contains(got, "TODO") {
		t.Fatalf("did not instruct the author:\n%s", got)
	}
}

// The snake_case of a unit name names the Python and Rust test functions. It doubled the
// separator (`My-Name` → `my__name`) and split an acronym letter by letter
// (`HTTPServer` → `h_t_t_p_server`): a test name nobody would write, and in Python one
// that a linter flags.
func TestSnakeCaseOfAUnitName(t *testing.T) {
	t.Run("NWTMN-B11: A unit name becomes snake_case with one separator and whole acronyms", func(t *testing.T) {})
	for in, want := range map[string]string{
		"My-Name":       "my_name",
		"HTTPServer":    "http_server",
		"calcTotal":     "calc_total",
		"CalcTotal":     "calc_total",
		"parseJSON":     "parse_json",
		"getHTTPCode":   "get_http_code",
		"my name.v2":    "my_name_v2",
		"My_Name":       "my_name",
		"version2Beta":  "version2_beta",
		"calc -- total": "calc_total",
		"-lead":         "lead",
	} {
		if got := toSnake(in); got != want {
			t.Errorf("toSnake(%q) = %q, want %q", in, got, want)
		}
	}
	if body := testBody("python", "HTTPServer", "XXXXX"); !strings.Contains(body, "def test_http_server(") {
		t.Errorf("the python body must use the snake name:\n%s", body)
	}
}

func TestCatalogTiesRulesToWhatTheyUse(t *testing.T) {
	t.Run("NWTMN-B12: The catalog ties rules to what they use", func(t *testing.T) {})
	realizes := map[string]string{}
	for _, s := range specTemplate.sections {
		realizes[s.Key] = s.Realizes
	}
	if realizes["validations"] != "V" || realizes["presentation-validations"] != "P" || realizes["rule-uses"] != "" {
		t.Errorf("V, P and no letter, got %q %q %q", realizes["validations"], realizes["presentation-validations"], realizes["rule-uses"])
	}
	for name, p := range specPresets {
		if !slices.Contains(p.Sections, "rule-uses") {
			t.Errorf("preset %s lacks rule-uses", name)
		}
	}
	for name, want := range map[string][]string{"screen": {"validations", "presentation-validations"}, "component": {"presentation-validations"}, "validation": {"validations"}} {
		for _, w := range want {
			if !slices.Contains(specPresets[name].Sections, w) {
				t.Errorf("preset %s lacks %s", name, w)
			}
		}
	}
	sections, order, err := resolveSectionsWithPreset(specTemplate, "screen", nil, nil)
	if err != nil {
		t.Fatal(err)
	}
	out := renderArtifact(specTemplate, "Pay", "PAYMT", "Pay.spec.md", t.TempDir(), sections, order, &config.Config{Lang: "en"})
	for _, w := range []string{"## Validations\n\n| Rule | Field | Condition | Behavior |", "| `PAYMT-V01` |",
		"## Presentation validations\n\n| Rule | Prop/State | Condition | Appearance |", "| `PAYMT-P01` |",
		"## Rule uses\n\n| Rule | Uses |", "| `PAYMT-B01` |"} {
		if !strings.Contains(out, w) {
			t.Errorf("the screen spec lacks %q", w)
		}
	}
}
