package governance

// specGuide é a régua universal da fase ESPECIFICAR. Destila a doutrina agnóstica de
// "o que é uma boa spec" — sem amarrar a stack. O projeto especializa no seu próprio
// guide de spec (a camada 'guide' do anchors.yaml); este é o piso comum.
const specGuide = `# Spec guide (the ruler of the SPECIFY phase)

The spec is a unit's SOURCE OF TRUTH. The plan decided THAT it must exist;
the spec decides HOW it behaves — in text, never in code. From the spec are born the
code, the feature and the test; if any of them diverges from it, it is the spec that is confronted.

## The rule that is not broken

DESCRIBE BEHAVIOUR, NOT IMPLEMENTATION. The spec is textual and explanatory. No
code blocks, type signatures, file trees or library names. If
you felt the urge to paste code, that is content of the CODE, not of the spec.

FRAMEWORK-AGNOSTIC. The corollary that escapes most often: a spec cannot depend on the
dialect of the tool that implements it today. Switching frameworks cannot invalidate the
spec — if it does, it was describing the tool, not the decision.

  ✗ "uses '.identifier(['goalId'])'"      ✓ "the identity is 'goalId', generated by the client"
  ✗ "'allow.owner()'"                     ✓ "only the owner reads and writes their own record"
  ✗ "exposes 'queryField'"                ✓ "the query is exposed to the client"
  ✗ "Amplify secondary index"             ✓ "answers the question 'X of a user'"

THE TEST: if the project migrated frameworks tomorrow, would this sentence still be true?
If not, it describes the tool. The decision (what the identity is, who sees what,
which questions the data answers) survives the migration; the API name does not.

Naming the tool is legitimate in ONE place: the Implementation Notes, where you record
how the decision was materialized today — and it is clear that this is the present, not the rule.

## Identity (the connecting thread)

Each specifiable unit receives a short, unique and STABLE CODE — it does not change if
the file is renamed. That code prefixes every internal item (rules,
states, messages) and crosses spec → feature → test. It is what lets you, given a
code, find the spec, the scenario and the test. (The exact format of the code is the project's;
the EXISTENCE of a stable and unique ID is universal.)

## Specialize the spec by the ORIGIN OF THE VARIATION

A spec is not all alike — it specializes according to what makes the unit vary:
- A FLOW/STATE unit — varies by internal state and navigation, fetches data. The
  spec focuses on states, transitions and the data contract.
- A COMPOSITION/CONTRACT unit — varies by input (parameters/props), does not fetch
  data, emits events/callbacks. The spec focuses on the input contract, the variation
  matrix and the emitted events.
(The names "screen"/"component" are the project's; the distinction is universal.)

## Sections (adopt the ones that apply to the unit)

1. Header with the CODE and the purpose in one sentence.
2. Overview — what the unit does and for whom.
3. Rules — each rule is a catalogued item, each with its ID (permissions,
   validations, actions, behaviours). Each item is a SECTION with a heading containing the
   code (not a loose bullet in a list) — because the feature and the test will reference
   the item by the heading. The EXACT FORMAT of the heading (markdown level, punctuation) is
   defined by YOUR project's completeness gate — run 'anchors check' to
   confirm the spec passes; if it fails, the gate's message tells the expected format.
   Typing the rules helps coverage later.
4. States — for units with state: each state, its entry condition, and what
   is visible/hidden/disabled in it.
5. State flow — the transitions between the states.
6. Data contract — every dynamic datum displayed: origin, requiredness, format,
   default. Cautions that prevent real bugs: explicit TIMEZONE in dates; translated
   enums (backend↔interface) documented; a computed field points at the function.
7. Data states — one item per conditional branch / per enum value (empty, error,
   loading, each variant).
8. Messages — the literal text shown to the user is catalogued ONCE, here. It is the single
   source of copy; rules and actions only REFERENCE the message code, they never duplicate the
   text.
9. Implementation notes — honest TODOs, decisions, assumed ambiguities.
10. Change history.

## Spec rules

- It catalogues everything that varies. Each state, validation, action, message and data field
  becomes an item with an ID — because the FEATURE will demand a scenario for each of them.
- Copy is a single source. The user-facing text lives only in the Messages; never repeat the sentence
  in another section — reference the code.
- Ambiguity becomes a TODO, never a guess (inherited from the plan).
- Co-location. The spec lives beside the artifact it describes.
- A rule that holds for OTHER units is not this spec's: it is product doctrine. Reference
  it with ` + "`@realizes`" + ` instead of writing it again here.

## The rule that is not yours: product doctrine

A spec describes ONE unit. When a rule holds for several — "the credit limit applies to
signup, simulation and approval" — it belongs to none of them, and writing it into each
makes the copies diverge at the first change.

It lives in ` + "`product/<name>.doctrine.md`" + `, and the spec points at it on the line
of the rule that concretises it:

    ### CRED-V01 — disables submit when the amount is above the limit   @realizes LIMIT-R03

State HERE only what is specific to this unit. The example above says WHAT THIS SCREEN
DOES; the shared rule ("the limit is never exceeded") stays in the doctrine, said once.

Copying the doctrine's text back is the defect the axis exists to eliminate, and
` + "`doctrine-not-duplicated`" + ` charges it. Read ` + "`anchors guide product`" + `
before writing or realizing doctrine.

## Anti-patterns (refuse them)

- A code block in the spec → that is implementation; describe the behaviour.
- A state without an entry condition → it cannot be tested; declare when it happens.
- Copy duplicated in two sections → it will diverge; centralize it in the Messages.
- A requirement without an ID → it becomes invisible to the feature and the test; give it a code.
- The same rule written in two specs → it is product doctrine; move it to ` + "`product/`" + ` and reference it.

## Project specialization

This is the universal floor. Your project may have a more detailed spec guide (see the
'guide' layer in anchors.yaml) with extra sections (accessibility, navigation,
visual reference) and the exact format of the identity code. Read it and follow it; if it
does not exist, this guide is enough — and warn the user that the specific ruler is a loose
end.
`
