// @anchors
//   ref: GVGDG

package governance

// specGuide é a régua universal da fase ESPECIFICAR. Destila a doutrina agnóstica de
// "o que é uma boa spec" — sem amarrar a stack. O projeto especializa no seu próprio
// guide de spec (a camada 'guide' do anchors.yaml); este é o piso comum.
const specGuide = `# Spec guide (the ruler of the SPECIFY phase)

The spec is a unit's SOURCE OF TRUTH. The plan decided THAT it must exist;
the spec decides HOW it behaves — in text, never in code. From the spec are born the
code, the feature and the test; if any of them diverges from it, it is the spec that is confronted.

## The rule that is not broken

DESCRIBE BEHAVIOUR, NOT IMPLEMENTATION. The spec is textual and explanatory. No
code blocks, type signatures, file trees or library names. If
you felt the urge to paste code, that is content of the CODE, not of the spec.

FRAMEWORK-AGNOSTIC. The corollary that escapes most often: a spec cannot depend on the
dialect of the tool that implements it today. Switching frameworks cannot invalidate the
spec — if it does, it was describing the tool, not the decision.

  ✗ "uses '.identifier(['goalId'])'"      ✓ "the identity is 'goalId', generated by the client"
  ✗ "'allow.owner()'"                     ✓ "only the owner reads and writes their own record"
  ✗ "exposes 'queryField'"                ✓ "the query is exposed to the client"
  ✗ "Amplify secondary index"             ✓ "answers the question 'X of a user'"

THE TEST: if the project migrated frameworks tomorrow, would this sentence still be true?
If not, it describes the tool. The decision (what the identity is, who sees what,
which questions the data answers) survives the migration; the API name does not.

Naming the tool is legitimate in ONE place: the Implementation Notes, where you record
how the decision was materialized today — and it is clear that this is the present, not the rule.

## Identity (the connecting thread)

Each specifiable unit receives a short, unique and STABLE CODE — it does not change if
the file is renamed. That code prefixes every internal item (rules,
states, messages) and crosses spec → feature → test. It is what lets you, given a
code, find the spec, the scenario and the test. (The exact format of the code is the project's;
the EXISTENCE of a stable and unique ID is universal.)

## Specialize the spec by the ORIGIN OF THE VARIATION

A spec is not all alike — it specializes according to what makes the unit vary:
- A FLOW/STATE unit — varies by internal state and navigation, fetches data. The
  spec focuses on states, transitions and the data contract.
- A COMPOSITION/CONTRACT unit — varies by input (parameters/props), does not fetch
  data, emits events/callbacks. The spec focuses on the input contract, the variation
  matrix and the emitted events.
(The names "screen"/"component" are the project's; the distinction is universal.)
- An API unit (an HTTP operation) — varies by request. The spec says what an OpenAPI
  says of the operation, and what it does not: ` + "`Endpoint`" + ` (method, path, a stable
  operation name), ` + "`Parameters`" + `, ` + "`Request Body`" + ` and ` + "`Responses`" + `, ` + "`Error Responses`" + ` (each
  refusal with its status, a stable error code and the message), ` + "`Security`" + ` and
  ` + "`Limits`" + ` — ` + "`anchors new spec --preset api`" + `. The body and each response CITE their
  contract by code: the contract is the model's spec, in the domain, whose ` + "`Domain`" + `
  table lists the fields, with ` + "`Type`" + ` and ` + "`Required`" + ` columns. The API spec says WHICH
  contract; the contract says the fields — one place each. The project's OpenAPI is
  compiled from these specs by ` + "`anchors docs build`" + `.
- Any unit that reads ENVIRONMENT VARIABLES declares them in ` + "`Environment Variables`" + `:
  each with its type, whether it is required, its default, its possible values and
  whether it is deprecated (` + "`yes: use NEW_NAME`" + `). It is the contract with whoever deploys:
  ` + "`env-declared`" + ` confronts it with the code both ways — a variable read and not declared, or
  declared and no longer read —, and the project's variables page is compiled from it.

## Sections (adopt the ones that apply to the unit)

1. Header with the CODE and the purpose in one sentence.
2. Overview — what the unit does and for whom.
3. Rules — each rule is a catalogued item, each with its ID (permissions,
   validations, actions, behaviours). Each item is a SECTION with a heading containing the
   code (not a loose bullet in a list) — because the feature and the test will reference
   the item by the heading. The EXACT FORMAT of the heading (markdown level, punctuation) is
   defined by YOUR project's completeness gate — run 'anchors check' to
   confirm the spec passes; if it fails, the gate's message tells the expected format.
   Typing the rules helps coverage later.
4. States — for units with state: each state, its entry condition, and what
   is visible/hidden/disabled in it. In a VISUAL unit (a screen, a component), every state
   registered here is strongly recommended to be proven by VISUAL REGRESSION: a capture
   compared with a baseline image of that state — see ` + "`anchors guide test`" + `. It is what keeps
   each state looking as the spec says; ` + "`vr-states-covered`" + ` asks it of every state. A state with
   no visual value of its own (a transient loading) carries ` + "`@no-vr: <reason>`" + ` on its line.
   In a visual unit, every VALIDATION (and presentation validation) changes the screen, so
   it is the TRIGGER of a State Flow row — from the state it is checked in to the state it
   leads to — and is proven by that state's capture; one that changes no state says
   ` + "`@no-state: <reason>`" + ` (` + "`validation-transitions`" + `). Every ERROR shows on the screen as a
   message: it cites the code of the User Message it shows, or says ` + "`@no-message: <reason>`" + `
   (` + "`error-message-declared`" + `); the messages are captured like the states.
5. State flow — the transitions between the states.
6. Data contract — every dynamic datum displayed: origin, requiredness, format,
   default. Cautions that prevent real bugs: explicit TIMEZONE in dates; translated
   enums (backend↔interface) documented; a computed field points at the function.
7. Data states — one item per conditional branch / per enum value (empty, error,
   loading, each variant).
8. Validations (` + "`V`" + `) — a rule that checks a datum: one row per rule, ` + "`| Rule | Field | Condition | Behavior |`" + `.
9. Presentation validations (` + "`P`" + `) — a rule that changes what the unit SHOWS from a prop or a
   state: ` + "`| Rule | Prop/State | Condition | Appearance |`" + `. Apart from 8, since both live in one screen.
10. Rule uses — ties every other rule (behaviours, states, errors, actions) to what it uses:
   ` + "`| Rule | Uses |`" + `, with fields by name, the spec's own codes and ` + "`DEPn`" + ` rows. Sections 8–10
   are what say which rules a changed field reaches: the rule's code first, what it uses second.
   ` + "`rule-uses-declared`" + ` asks every rule to say what it uses; a rule that uses nothing carries
   ` + "`@no-uses: <why>`" + ` on the rule's OWN row, where the rule is declared — not in the Rule uses
   table, which only lists rules that do use something. ` + "`rule-uses-resolve`" + ` asks that each use
   exists in the spec: a field is the FIRST CELL of a row of another table of the spec (Validations,
   Domain, a contract table…) or a backticked name in a heading — a name written only in prose does
   not resolve. When a field (or a state) changes,
   ` + "`contract-impact`" + ` names the rules that use it and their tests, and ` + "`anchors test`" + ` runs them.
11. Messages — the literal text shown to the user is catalogued ONCE, here. It is the single
   source of copy; rules and actions only REFERENCE the message code, they never duplicate the
   text.
12. Implementation notes — honest TODOs, decisions, assumed ambiguities.
13. Change history.

## Writing it: every section, every variation, then a review

The spec is the piece everything else is confronted with. A rule missing here is a
scenario, a test and a check that will never exist: the gates prove that the code does
what the spec says, never that the spec said enough. Most defects that reach users are
a rule nobody wrote. So do not stop at the first draft — write it in four passes.

1. WALK EVERY SECTION. List them (` + "`anchors new spec --list-sections`" + `) and, for
   each one, ask whether it applies to this unit, and if it does, what goes in it. A
   section skipped by reflex is where the missing rule hides. Ask in particular:
   - Every INPUT the unit accepts (argument, flag, parameter, field): which rule says
     what it does, and what happens to a value outside the domain? An input no rule
     mentions is an input nobody decided — and the code will decide it by accident.
   - Every EFFECT (a file written, a command run, a record changed, a message sent):
     which rule says its limit — where it writes, and what it must NEVER touch? A
     prohibition is a rule (` + "`X`" + `); a side effect with no written limit is the
     defect no test of the happy path finds.
   - Every FAILURE: how the unit fails, and what the caller sees.
   - Every STATE the unit reads that another unit also reads or writes: which rule says
     the two agree?
2. DERIVE THE VARIATIONS. For each rule, ask what varies around it, and write each
   variation that changes the behaviour as a rule of its own:
   - each value of an enum, each state of the input — empty, absent, several at once,
     in another format, changed or removed while the unit works;
   - each environment the unit runs in — another operating system, another user or
     process acting at the same time, a file that disappeared;
   - each combination of options that are not independent.
   A variation that does NOT change the behaviour is said on the rule ("whatever the
   order of the files"), so the reader knows it was considered.
3. GENERALIZE. When a rule is one instance of a wider truth, write the wider truth as
   an invariant (` + "`I`" + `) and keep the instance as its consequence:
     ✗ "under --index, this gate reads the staged file"
     ✓ "under --index, nothing a gate reads comes from the tree" — and this gate's rule
       is one case of it
   The invariant covers the variation nobody listed yet: its test runs every case, and
   the next variation is caught there instead of arriving as the next defect. When
   several rules say the same thing about different cases, they are an invariant
   waiting to be written.
4. REVIEW WHAT YOU WROTE, before the feature is written. Read each rule again and ask:
   - Does it state the INTENT, or the mechanism that implements it?
       ✗ "the test's body ends at the first closer back at its indentation"
       ✓ "the test's body is everything the test runs"
     A rule that describes the mechanism is proven by any test of that mechanism,
     right or wrong: the unit stays green and wrong together.
   - From this rule alone, could someone who never saw the code say what must happen
     in a case you did not think of?
   - Is it silent about the rest? "Narrows to the changed files" says nothing of the
     file that was asked for and left out — say what the user is told.
   - Is anything the unit does left without a rule? When the code exists, walk it:
     every branch, every input, every effect.
   A rule fixed now costs a line; fixed after a defect, it costs the defect.

WHEN A DEFECT REACHES YOU, it is a rule that was not written. Before fixing it, find the
rule it breaks — and the invariant it is one case of (pass 3) — and write them; then the
scenarios and the tests, which will fail; then the fix. Fixing the reported case alone
leaves its siblings to arrive one by one.

## Spec rules

- It catalogues everything that varies. Each state, validation, action, message and data field
  becomes an item with an ID — because the FEATURE will demand a scenario for each of them.
- Copy is a single source. The user-facing text lives only in the Messages; never repeat the sentence
  in another section — reference the code.
- Ambiguity becomes a TODO, never a guess (inherited from the plan).
- Co-location. The spec lives beside the artifact it describes.
- A rule that holds for OTHER units is not this spec's: it is product doctrine. Reference
  it with ` + "`@realizes`" + ` instead of writing it again here.
- A rule this spec already states under ANOTHER letter is aliased, not rewritten. The
  failure gates look for failures under ` + "`-E`" + `; when the failure is already a behaviour
  (` + "`-B`" + `), catalogue it as an alias on the rule's line:
      | ` + "`CODE-E01`" + ` | REF[CODE-B05]: <why B05 is this failure> |
  The alias needs no scenario — the target's scenario proves it — and it must point at a
  rule this spec defines (not at another alias), with a reason, or ` + "`spec-feature-match`" + ` fails.
- A unit that handles no failure says so. When every match the failure gates find is
  normal flow (a map created on first use, a pattern that did not match), close the
  section with the reason instead of inventing a failure:
      ## Errors
      none — <why the matches are not defences>

## The rule that is not yours: product doctrine

A spec describes ONE unit. When a rule holds for several — "the credit limit applies to
signup, simulation and approval" — it belongs to none of them, and writing it into each
makes the copies diverge at the first change.

It lives in ` + "`product/<name>.doctrine.md`" + `, and the spec points at it on the line
of the rule that concretises it:

    ### CRED-V01 — disables submit when the amount is above the limit   @realizes LIMIT-R03

State HERE only what is specific to this unit. The example above says WHAT THIS SCREEN
DOES; the shared rule ("the limit is never exceeded") stays in the doctrine, said once.

Copying the doctrine's text back is the defect the axis exists to eliminate, and
` + "`doctrine-not-duplicated`" + ` charges it. Read ` + "`anchors guide product`" + `
before writing or realizing doctrine.

## Anti-patterns (refuse them)

- A code block in the spec → that is implementation; describe the behaviour.
- A state without an entry condition → it cannot be tested; declare when it happens.
- Copy duplicated in two sections → it will diverge; centralize it in the Messages.
- A requirement without an ID → it becomes invisible to the feature and the test; give it a code.
- The same rule written in two specs → it is product doctrine; move it to ` + "`product/`" + ` and reference it.

## Project specialization

This is the universal floor. Your project may have a more detailed spec guide (see the
'guide' layer in anchors.yaml) with extra sections (accessibility, navigation,
visual reference) and the exact format of the identity code. Read it and follow it; if it
does not exist, this guide is enough — and warn the user that the specific ruler is a loose
end.
`
