package scan

import (
	"strings"
	"testing"
)

// The jq program of blue-eyes' `anchors-board.yml`, trimmed: a body line starting with
// `parent:` that is not a header declaration.
const boardWorkflow = `# Anchors — board
# anchors:template — generated by anchors.
# FNDTN-F04 is how a phase is written.
jobs:
  board:
    steps:
      - run: |
          jq '{
                parent: ([$cod[0][] | select(.code == $i.code) | .parent // ""] | first // "")
              }'
`

func TestAnchorsHeader_ignoresTheSharedCodeFlagAndProse(t *testing.T) {
	t.Run("UPOWP-B03: The shared-code flag and prose do not open a header", func(t *testing.T) {})
	if h := AnchorsHeader([]byte("// @anchors-shared-code\n// parent: X\n")); h != nil {
		t.Errorf("`@anchors-shared-code` does not open a header, got %q", h)
	}
	if h := AnchorsHeader([]byte("the `@anchors` header\nparent: X\n")); h != nil {
		t.Errorf("prose does not open a header, got %q", h)
	}
}

func TestAnchorsHeader_endsWithItsComment(t *testing.T) {
	t.Run("UPOWP-B04: An HTML or block-comment header ends with its comment", func(t *testing.T) {})
	t.Run("UPOWP-I01: Nothing after the header's comment belongs to it", func(t *testing.T) {})
	for src, want := range map[string]string{
		"<!-- @anchors\n code: X\n-->\ncode: Y": "<!-- @anchors\n code: X\n-->",
		"/* @anchors\n code: X\n*/\ncode: Y":    "/* @anchors\n code: X\n*/",
		"<!-- @anchors code: X -->\ncode: Y":    "<!-- @anchors code: X -->",
	} {
		got := string(AnchorsHeader([]byte(src)))
		if got != want {
			t.Errorf("header of %q = %q, want %q", src, got, want)
		}
		if strings.Contains(got, "code: Y") {
			t.Errorf("the body line leaked into the header of %q", src)
		}
	}
}

func TestAnchorsHeader_lineCommentsEndAtTheFirstNonComment(t *testing.T) {
	t.Run("UPOWP-B05: A line-comment header ends at the first line that is not a comment", func(t *testing.T) {})
	if got := string(AnchorsHeader([]byte("# @anchors\n#  code: X\n\n# after"))); got != "# @anchors\n#  code: X" {
		t.Errorf("the line-comment header should stop at the blank line, got %q", got)
	}
}

func TestAnchorsHeader_unclosedRunsToTheEnd(t *testing.T) {
	t.Run("UPOWP-B06: A header comment that never closes runs to the end of the file", func(t *testing.T) {})
	src := "<!-- @anchors\n code: X\nnever closes"
	if got := string(AnchorsHeader([]byte(src))); got != src {
		t.Errorf("an unclosed header runs to the end of the file, got %q", got)
	}
}

func TestIsUpstreamOwned(t *testing.T) {
	t.Run("UPOWP-B01: Only a marked workflow is owned upstream", func(t *testing.T) {})
	marked := []byte("# anchors:template\non: push\n")
	if !IsUpstreamOwned(".github/workflows/anchors-claim.yml", marked) {
		t.Error("a marker-carrying workflow is upstream-owned")
	}
	if IsUpstreamOwned(".github/workflows/ci.yml", []byte("on: push\n")) {
		t.Error("a workflow without the marker is the project's")
	}
	if IsUpstreamOwned("docs/anchors-board.yml", marked) {
		t.Error("the marker outside .github/workflows does not make a file upstream-owned")
	}
}

func TestIsUpstreamOwned_windowsPath(t *testing.T) {
	t.Run("UPOWP-B02: A Windows path under the workflow directory is recognised", func(t *testing.T) {})
	if !IsUpstreamOwned(`.github\workflows\a.yml`, []byte("# anchors:template\n")) {
		t.Error("the backslash form of a workflow path is the same file")
	}
}

func TestIsUpstreamOwned_nameDoesNotCount(t *testing.T) {
	t.Run("UPOWP-X01: Only the marker and the directory decide ownership", func(t *testing.T) {})
	if IsUpstreamOwned(".github/workflows/anchors-board.yml", []byte("on: push\n")) {
		t.Error("an `anchors-` name without the marker is the project's file")
	}
}
