package scan

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/co2-lab/anchors/internal/config"
)

// The jq program of blue-eyes' `anchors-board.yml`, trimmed: a body line starting with
// `parent:` that is not a header declaration.
const boardWorkflow = `# Anchors — board
# anchors:template — generated by anchors.
# FNDTN-F04 is how a phase is written.
jobs:
  board:
    steps:
      - run: |
          jq '{
                parent: ([$cod[0][] | select(.code == $i.code) | .parent // ""] | first // "")
              }'
`

func TestParentDe_onlyInsideTheHeader(t *testing.T) {
	if p := parentDe([]byte(boardWorkflow)); p != "" {
		t.Errorf("a `parent:` in a workflow's body is not a header declaration, got %q", p)
	}
	spec := "<!-- @anchors\n  code: INMTN\n  parent: DTBSA-F01\n  layer: lambdas\n-->\n# InstanceMetrics\n\nparent: NOPE-F09\n"
	if p := parentDe([]byte(spec)); p != "DTBSA-F01" {
		t.Errorf("the header's parent should be read, got %q", p)
	}
	code := "// @anchors\n//   ref: PRICX\n//   parent: PRICX-F02\npackage p\n\n// parent: NOPE-F09\n"
	if p := parentDe([]byte(code)); p != "PRICX-F02" {
		t.Errorf("a line-comment header's parent should be read, got %q", p)
	}
	noParent := "<!-- @anchors\n  code: INMTN\n-->\n# InstanceMetrics\n\nparent: NOPE-F09\n"
	if p := parentDe([]byte(noParent)); p != "" {
		t.Errorf("the HTML header ends at `-->`, got %q", p)
	}
	noParentCode := "// @anchors\n//   ref: PRICX\npackage p\n\n// parent: NOPE-F09\n"
	if p := parentDe([]byte(noParentCode)); p != "" {
		t.Errorf("a line-comment header ends at the first non-comment line, got %q", p)
	}
	oneLine := "<!-- @anchors parent: X -->\nparent: NOPE-F09\n"
	if p := parentDe([]byte(oneLine)); p != "" {
		t.Errorf("a one-line header closes on its own line, got %q", p)
	}
}

func TestAnchorsHeader_ignoresTheSharedCodeFlagAndProse(t *testing.T) {
	if h := AnchorsHeader([]byte("// @anchors-shared-code\n// parent: X\n")); h != nil {
		t.Errorf("`@anchors-shared-code` does not open a header, got %q", h)
	}
	if h := AnchorsHeader([]byte("the `@anchors` header\nparent: X\n")); h != nil {
		t.Errorf("prose does not open a header, got %q", h)
	}
}

func TestIsUpstreamOwned(t *testing.T) {
	marked := []byte("# anchors:template\non: push\n")
	if !IsUpstreamOwned(".github/workflows/anchors-claim.yml", marked) {
		t.Error("a marker-carrying workflow is upstream-owned")
	}
	if IsUpstreamOwned(".github/workflows/ci.yml", []byte("on: push\n")) {
		t.Error("a workflow without the marker is the project's")
	}
	if IsUpstreamOwned("docs/anchors-board.yml", marked) {
		t.Error("the marker outside .github/workflows does not make a file upstream-owned")
	}
}

// A vendored workflow enters the map with no scenario codes of its own: the examples in its
// comments are the Anchors project's vocabulary.
func TestWalk_upstreamWorkflowCarriesNoCodes(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, ".github/workflows"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, ".github/workflows/anchors-board.yml"), []byte(boardWorkflow), 0o644); err != nil {
		t.Fatal(err)
	}
	cfg := &config.Config{Layers: map[string]config.Layer{
		"workflow": {Pattern: ".github/workflows/*.yml", Kind: "code"},
	}}
	files, err := Walk(root, cfg)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 {
		t.Fatalf("expected the workflow in the scan, got %v", files)
	}
	f := files[0]
	if !f.Upstream || len(f.Codes) != 0 || f.Parent != "" {
		t.Errorf("expected upstream, no codes, no parent; got upstream=%v codes=%v parent=%q", f.Upstream, f.Codes, f.Parent)
	}
}
