// @anchors
//   code: UPTSP
//   ref: UPOWP

package scan

import (
	"strings"
	"testing"
)

// The jq program of the reference app's `anchors-board.yml`, trimmed: a body line starting with
// `parent:` that is not a header declaration.
const boardWorkflow = `# Anchors — board
# anchors:template — generated by anchors.
# FNDTN-W04 is how a phase is written.
jobs:
  board:
    steps:
      - run: |
          jq '{
                parent: ([$cod[0][] | select(.code == $i.code) | .parent // ""] | first // "")
              }'
`

func TestAnchorsHeader_ignoresTheSharedCodeFlagAndProse(t *testing.T) {
	t.Run("UPOWP-B03: The shared-code flag and prose do not open a header", func(t *testing.T) {})
	if h := AnchorsHeader([]byte("// @anchors-shared-code\n// parent: X\n")); h != nil {
		t.Errorf("`@anchors-shared-code` does not open a header, got %q", h)
	}
	if h := AnchorsHeader([]byte("the `@anchors` header\nparent: X\n")); h != nil {
		t.Errorf("prose does not open a header, got %q", h)
	}
}

func TestAnchorsHeader_endsWithItsComment(t *testing.T) {
	t.Run("UPOWP-B04: An HTML or block-comment header ends with its comment", func(t *testing.T) {})
	t.Run("UPOWP-I01: Nothing after the header's comment belongs to it", func(t *testing.T) {})
	for src, want := range map[string]string{
		"<!-- @anchors\n code: X\n-->\ncode: Y": "<!-- @anchors\n code: X\n-->",
		"/* @anchors\n code: X\n*/\ncode: Y":    "/* @anchors\n code: X\n*/",
		"<!-- @anchors code: X -->\ncode: Y":    "<!-- @anchors code: X -->",
	} {
		got := string(AnchorsHeader([]byte(src)))
		if got != want {
			t.Errorf("header of %q = %q, want %q", src, got, want)
		}
		if strings.Contains(got, "code: Y") {
			t.Errorf("the body line leaked into the header of %q", src)
		}
	}
}

func TestAnchorsHeader_lineCommentsEndAtTheFirstNonComment(t *testing.T) {
	t.Run("UPOWP-B05: A line-comment header ends at the first line that is not a comment", func(t *testing.T) {})
	if got := string(AnchorsHeader([]byte("# @anchors\n#  code: X\n\n# after"))); got != "# @anchors\n#  code: X" {
		t.Errorf("the line-comment header should stop at the blank line, got %q", got)
	}
}

func TestAnchorsHeader_unclosedRunsToTheEnd(t *testing.T) {
	t.Run("UPOWP-B06: A header comment that never closes runs to the end of the file", func(t *testing.T) {})
	src := "<!-- @anchors\n code: X\nnever closes"
	if got := string(AnchorsHeader([]byte(src))); got != src {
		t.Errorf("an unclosed header runs to the end of the file, got %q", got)
	}
}

func TestIsUpstreamOwned(t *testing.T) {
	t.Run("UPOWP-B01: Only a marked workflow is owned upstream", func(t *testing.T) {})
	marked := []byte("# anchors:template\non: push\n")
	if !IsUpstreamOwned(".github/workflows/anchors-claim.yml", marked) {
		t.Error("a marker-carrying workflow is upstream-owned")
	}
	if IsUpstreamOwned(".github/workflows/ci.yml", []byte("on: push\n")) {
		t.Error("a workflow without the marker is the project's")
	}
	if IsUpstreamOwned("docs/anchors-board.yml", marked) {
		t.Error("the marker outside .github/workflows does not make a file upstream-owned")
	}
}

func TestIsUpstreamOwned_windowsPath(t *testing.T) {
	t.Run("UPOWP-B02: A Windows path under the workflow directory is recognised", func(t *testing.T) {})
	if !IsUpstreamOwned(`.github\workflows\a.yml`, []byte("# anchors:template\n")) {
		t.Error("the backslash form of a workflow path is the same file")
	}
}

func TestIsUpstreamOwned_nameDoesNotCount(t *testing.T) {
	t.Run("UPOWP-X01: Only the marker and the directory decide ownership", func(t *testing.T) {})
	if IsUpstreamOwned(".github/workflows/anchors-board.yml", []byte("on: push\n")) {
		t.Error("an `anchors-` name without the marker is the project's file")
	}
}

func TestAnchorsHeader_onlyAtTheTop(t *testing.T) {
	t.Run("UPOWP-B07: Only a header at the top is the header, unless it says why it stands lower", func(t *testing.T) {})
	for _, src := range []string{
		"#!/usr/bin/env node\n// a note\n\n// @anchors\n//   ref: X\n",
		"/**\n * @vitest-environment jsdom\n * why the DOM\n */\n// @anchors\n//   ref: X\n",
		"<!-- a note\nspanning lines\n-->\n<!-- @anchors\n  code: X\n-->\n",
		"# language: en\n# @anchors\n#   ref: X\n",
	} {
		if AnchorsHeader([]byte(src)) == nil || HeaderOffTop([]byte(src)) {
			t.Errorf("a header after comments only is the header: %q", src)
		}
	}
	low := "'use client'\n// @anchors\n//   ref: X\n"
	if AnchorsHeader([]byte(low)) != nil || !HeaderOffTop([]byte(low)) {
		t.Errorf("a header after a directive is not the header, and is reported off the top")
	}
	fixed := "'use client'\n// @anchors\n//   ref: X\n//   @fixed-header: the directive must be the first statement\n"
	if h := AnchorsHeader([]byte(fixed)); !strings.Contains(string(h), "ref: X") || HeaderOffTop([]byte(fixed)) {
		t.Errorf("a declared header below the top is the header, got %q", h)
	}
	bare := "package x\n// @anchors\n//   ref: X\n//   @fixed-header:\n"
	if AnchorsHeader([]byte(bare)) != nil {
		t.Error("a bare @fixed-header declares nothing")
	}
	example := "// @anchors\n//   layer: real\n\npackage x\nconst g = `\n  // @anchors\n  //   layer: screen\n`\n"
	if h := string(AnchorsHeader([]byte(example))); !strings.Contains(h, "layer: real") || HeaderOffTop([]byte(example)) {
		t.Errorf("the top header wins over an example below, got %q", h)
	}
	if HeaderOffTop([]byte("package x\n")) {
		t.Error("a file with no block is not off the top")
	}
}

func TestAnchorsHeader_firstWordOpensIt(t *testing.T) {
	t.Run("UPOWP-B08: Only a comment whose first word is @anchors opens the header", func(t *testing.T) {})
	prose := "// Package recode renames a code across the header @anchors (code:/ref:), the\n// derived codes and the mentions.\npackage recode\n"
	if AnchorsHeader([]byte(prose)) != nil {
		t.Error("prose naming the header is no header")
	}
	if AnchorsHeader([]byte("// @anchors\n//   ref: RCRWR\n\npackage recode\n")) == nil {
		t.Error("a comment opening with @anchors opens the header")
	}
}
