package main

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/co2-lab/anchors/internal/config"
	"github.com/co2-lab/anchors/internal/initx"
)

const (
	gateStart = "<!-- gate-reference:start — generated by `go run ./tools/sitecli` from the gate catalog and the checker's spec; edit those, not this block -->"
	gateEnd   = "<!-- gate-reference:end -->"
	repoBlob  = "https://github.com/co2-lab/anchors/blob/main/"
)

// gateGroup is a section of the gate catalog on the site: the menu and the index list the
// gates under it.
type gateGroup struct {
	en, pt string
	gates  []string
}

// gateGroups is how the site groups the gates. A gate of the catalog that no group names
// lands in the last one, so a new gate is never left out of the menu.
var gateGroups = []gateGroup{
	{"The Unit & Structure", "A Unidade e Estrutura", []string{"unit-complete", "spec-has-code", "spec-complete", "feature-not-empty", "spec-feature-match", "feature-spec-match", "feature-test-match", "test-feature-match", "scenario-identity", "scenario-asserts", "scenario-type-aligned", "scenario-letter-declared", "code-reference-valid", "code-cataloged", "placeholder-filled", "header-valid", "header-layer-declared", "ref-resolves", "examples-match"}},
	{"Presentation & UI", "Apresentação e Telas", []string{"presentation-exhaustive", "presentation-conflict", "presentation-copy-single-source", "presentation-observable", "identity-consistent", "testid-consistent", "testid-queried-exists", "vr-baseline"}},
	{"Doctrine & Feature Flags", "Doutrina e Feature Flags", []string{"spec-doctrine-exists", "plan-doctrine-exists", "doctrine-realized", "doctrine-not-duplicated", "spec-realizes-doctrine", "flag-scenario-grammar", "flag-scenarios-complete", "flag-scenario-exists", "flag-scenario-governs", "flag-covered"}},
	{"Test Doubles & Mocks", "Dublês e Mocks", []string{"mock-stamped", "mock-typed", "mock-detect-covers-dialect"}},
	{"Failure & Governance", "Falhas e Governança", []string{"failure-declared", "failure-handled", "failure-logged", "region-pair-honored", "rule-types", "rule-implemented", "marker-parity", "obligation-honored", "updated-at-atual", "guide-checklist", "docs-fresh", "docs-covered", "doc-required", "doc-self-contained"}},
	{"Architectural Boundaries", "Fronteiras Arquiteturais", []string{"layer-boundary", "sibling-guard", "proof-crosses-boundary", "circular", "deadcode"}},
	{"AI Judgment & Review", "Julgamento por IA e Review", []string{"rule-fulfilled", "no-test-proof-real"}},
	{"Planning & Progress", "Planejamento e Progresso", []string{"phase-exists", "phase-ordered", "parent-valid", "plan-seeds-valid", "plan-source-declared", "plan-revised", "plan-change-justified", "open-questions-resolved", "progress-honest", "revision-orphans"}},
	{"Proof & Execution", "Prova e Execução", []string{"tests-green", "test-has-assertion", "test-exercises-unit", "test-ref-matches-unit", "evidence-fresh", "line-coverage", "branch-coverage", "coverage-delta", "mutation-score", "scenario-coverage", "single-test-per-unit", "test-level-codes", "test-traceable"}},
	{"Security & Hygiene", "Segurança e Higiene", []string{"no-secret-leaked", "dependency-vulnerable", "sbom-generated", "license-compatible", "no-duplication", "spellcheck"}},
	{"Rules Usage & Contracts", "Uso de Regras e Contratos", []string{"rule-uses-declared", "rule-uses-resolve", "rule-uses-implemented", "contract-impact", "contract-status-declared", "domain-declared", "count-honored", "pagination-honored", "route-declared", "route-exists", "dependency-honored", "trigger-declared", "value-anchored"}},
	{"Other gates", "Outros gates", nil},
}

var gateTexts = map[string]map[string]string{
	"en": {"dir": "en/gates", "prefix": "/docs/gates/", "check": "Checker", "run": "Command", "judgment": "Judgment", "judgmentV": "an AI or a person answers the question below, through `anchors judge`", "on": "Confronts", "blockNew": "Blocking by default — new project", "blockOld": "Blocking by default — existing project", "yes": "yes", "no": "no — informs", "presupposes": "Presupposes", "presupposesV": "until these are declared in `anchors.yaml`, the gate is pending and asks nothing", "review": "Review", "reviewV": "its targets are marked to review (`anchors review`)", "ask": "The question", "how": "How it measures", "declare": "Declaring it", "source": "Source", "checker": "checker", "spec": "its spec", "notSeeded": "Not in the default catalog: `init` does not seed it; a project declares it with `check:`.", "property": "Property", "value": "Value", "gate": "Gate", "measures": "What it measures"},
	"pt": {"dir": "pt/gates", "prefix": "/pt/docs/gates/", "check": "Verificação", "run": "Comando", "judgment": "Julgamento", "judgmentV": "uma IA ou uma pessoa responde a pergunta abaixo, via `anchors judge`", "on": "Confronta", "blockNew": "Bloqueante por padrão — projeto novo", "blockOld": "Bloqueante por padrão — projeto existente", "yes": "sim", "no": "não — informa", "presupposes": "Pressupõe", "presupposesV": "enquanto não forem declarados no `anchors.yaml`, o gate fica pendente e não cobra nada", "review": "Review", "reviewV": "seus alvos ficam marcados para revisar (`anchors review`)", "ask": "A pergunta", "how": "Como mede", "declare": "Como declarar", "source": "Fonte", "checker": "verificação", "spec": "sua spec (em inglês)", "notSeeded": "Fora do catálogo padrão: o `init` não o semeia; um projeto o declara com `check:`.", "property": "Propriedade", "value": "Valor", "gate": "Gate", "measures": "O que mede"},
}

// gatePage is one gate as the site shows it.
type gatePage struct {
	g          config.Gate
	blockNew   bool
	blockOld   bool
	seeded     bool
	sourceFile string // the checker's Go file, relative to the repo
}

// writeGates writes one page per gate of the catalog — and one per checker no catalog gate
// uses —, the index of both languages and the menu's gate groups.
func writeGates() (int, error) {
	all := map[string]bool{"spec": true, "feature": true, "test": true, "guide": true, "plan": true, "code": true, "doc": true, "product": true, "flag": true}
	old := map[string]bool{}
	for _, g := range initx.DefaultGates(all, false) {
		old[g.Name] = g.IsBlocking()
	}
	sources, err := checkerSources(filepath.Join("internal", "gate"))
	if err != nil {
		return 0, err
	}
	pages := map[string]gatePage{}
	used := map[string]bool{}
	for _, g := range initx.DefaultGates(all, true) {
		pages[g.Name] = gatePage{g: g, blockNew: g.IsBlocking(), blockOld: old[g.Name], seeded: true, sourceFile: sources[g.Check]}
		used[g.Check] = true
	}
	for check, file := range sources {
		if !used[check] {
			if _, taken := pages[check]; !taken {
				pages[check] = gatePage{g: config.Gate{Name: check, Check: check}, sourceFile: file}
			}
		}
	}

	groups := groupGates(pages)
	base := filepath.Join("site", "src", "content", "docs")
	n := 0
	for lang, t := range gateTexts {
		for name, p := range pages {
			path := filepath.Join(base, filepath.FromSlash(t["dir"]), name+".md")
			if err := writeGatePage(path, p, lang); err != nil {
				return n, err
			}
			n++
		}
		if err := writeGateIndex(filepath.Join(base, filepath.FromSlash(t["dir"])+".md"), groups, pages, lang); err != nil {
			return n, err
		}
	}
	return n, writeGateSidebar(filepath.Join("site", "src", "generated", "gates.json"), groups)
}

// groupGates places every page in its group, and the ones no group names in the last.
func groupGates(pages map[string]gatePage) []gateGroup {
	placed := map[string]bool{}
	var out []gateGroup
	for _, gr := range gateGroups {
		var members []string
		for _, m := range gr.gates {
			if _, ok := pages[m]; ok {
				members = append(members, m)
				placed[m] = true
			}
		}
		if gr.gates == nil {
			for name := range pages {
				if !placed[name] {
					members = append(members, name)
				}
			}
			sort.Strings(members)
		}
		if len(members) > 0 {
			out = append(out, gateGroup{gr.en, gr.pt, members})
		}
	}
	return out
}

func writeGatePage(path string, p gatePage, lang string) error {
	t := gateTexts[lang]
	g := p.g
	var b strings.Builder
	b.WriteString(gateStart + "\n\n")
	if d := g.Describe(); d != "" {
		b.WriteString(capitalize(strings.TrimSuffix(d, ".")) + ".\n\n")
	}
	if !p.seeded {
		b.WriteString(t["notSeeded"] + "\n\n")
	}
	b.WriteString("| " + t["property"] + " | " + t["value"] + " |\n| --- | --- |\n")
	switch {
	case g.Measures == config.MeasuresJudgment:
		b.WriteString("| " + t["judgment"] + " | " + t["judgmentV"] + " |\n")
	case g.Run != "":
		b.WriteString("| " + t["run"] + " | `" + escapeCell(g.Run) + "` |\n")
	case g.Check != "":
		b.WriteString("| " + t["check"] + " | `" + g.Check + "` |\n")
	}
	if len(g.On) > 0 {
		b.WriteString("| " + t["on"] + " | " + codeList(g.On) + " |\n")
	}
	if p.seeded {
		b.WriteString("| " + t["blockNew"] + " | " + yesNo(p.blockNew, t) + " |\n")
		b.WriteString("| " + t["blockOld"] + " | " + yesNo(p.blockOld, t) + " |\n")
	}
	if len(g.Presupposes) > 0 {
		b.WriteString("| " + t["presupposes"] + " | " + codeList(g.Presupposes) + " — " + t["presupposesV"] + " |\n")
	}
	if g.Review != nil {
		b.WriteString("| " + t["review"] + " | " + t["reviewV"] + " |\n")
	}
	b.WriteString("\n")
	if g.Ask != "" {
		b.WriteString("## " + t["ask"] + "\n\n> " + strings.ReplaceAll(strings.TrimSpace(g.Ask), "\n", "\n> ") + "\n\n")
	}
	spec := ""
	if p.sourceFile != "" {
		spec = strings.TrimSuffix(p.sourceFile, ".go") + ".spec.md"
		if _, err := os.Stat(spec); err != nil {
			spec = ""
		}
	}
	if lang == "en" && spec != "" {
		if ov := specOverview(spec); ov != "" {
			b.WriteString("## " + t["how"] + "\n\n" + ov + "\n\n")
		}
	}
	b.WriteString("## " + t["declare"] + "\n\n```yaml\ngates:\n  - name: " + g.Name + "\n")
	if len(g.On) > 0 {
		b.WriteString("    on: [" + strings.Join(g.On, ", ") + "]\n")
	}
	switch {
	case g.Measures == config.MeasuresJudgment:
		b.WriteString("    measures: judgment\n")
	case g.Run != "":
		b.WriteString("    run: " + fmt.Sprintf("%q", g.Run) + "\n")
	case g.Check != "":
		b.WriteString("    check: " + g.Check + "\n")
	}
	b.WriteString("```\n\n")
	if p.sourceFile != "" {
		b.WriteString(t["source"] + ": [" + t["checker"] + "](" + repoBlob + filepath.ToSlash(p.sourceFile) + ")")
		if spec != "" {
			b.WriteString(" · [" + t["spec"] + "](" + repoBlob + filepath.ToSlash(spec) + ")")
		}
		b.WriteString("\n\n")
	}
	b.WriteString(gateEnd)

	// English pages are the generated block alone: the prose they carried was a machine
	// translation of the Portuguese and mixed both languages. A Portuguese page keeps what
	// a person wrote after its own facts table.
	body := ""
	if lang == "pt" {
		if raw, err := os.ReadFile(path); err == nil {
			body = ptProse(string(raw))
		}
	}
	desc := g.Describe()
	if desc == "" {
		desc = "Gate " + g.Name
	}
	out := fmt.Sprintf("---\ntitle: %q\ndescription: %q\n---\n\n", "Gate: "+g.Name, capitalize(oneLine(desc)))
	out += b.String()
	if body != "" {
		out += "\n\n---\n\n" + body
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(strings.TrimRight(out, "\n")+"\n"), 0o644)
}

// ptProse is a Portuguese page's own text: what follows the generated block, or — on a
// page written before the generator — what follows its hand-made facts table, which the
// block replaces.
func ptProse(raw string) string {
	s := stripFrontmatter(raw)
	if i := strings.Index(s, gateEnd); i >= 0 {
		s = s[i+len(gateEnd):]
		s = strings.TrimSpace(s)
		return strings.TrimSpace(strings.TrimPrefix(s, "---"))
	}
	s = strings.TrimSpace(s)
	if strings.HasPrefix(s, ">") {
		if i := strings.Index(s, "\n---\n"); i >= 0 {
			s = s[i+5:]
		}
	}
	return strings.TrimSpace(s)
}

func writeGateIndex(path string, groups []gateGroup, pages map[string]gatePage, lang string) error {
	t := gateTexts[lang]
	title, desc, intro := "Gates Catalog", "Every gate Anchors ships, by group: what each measures and the kinds of artifact it confronts.",
		"Every gate below is generated from the catalog in the code. `anchors init` seeds the ones related to the layers and artifacts a project declares; `anchors doctor` lists the whole catalog, and `anchors check --all` names the gates that cover what the project declares but are not declared."
	if lang == "pt" {
		title, desc, intro = "Catálogo de Gates", "Todos os gates do Anchors, por grupo: o que cada um mede e os tipos de artefato que confronta.",
			"Cada gate abaixo é gerado do catálogo no código. O `anchors init` semeia os que têm relação com as camadas e artefatos que o projeto declara; o `anchors doctor` lista o catálogo inteiro, e o `anchors check --all` aponta os gates que cobrem o que o projeto declara mas não estão declarados."
	}
	var b strings.Builder
	fmt.Fprintf(&b, "---\ntitle: %q\ndescription: %q\n---\n\n%s\n\n%s\n\n", title, desc, gateStart, intro)
	for _, gr := range groups {
		label := gr.en
		if lang == "pt" {
			label = gr.pt
		}
		b.WriteString("## " + label + "\n\n| " + t["gate"] + " | " + t["on"] + " | " + t["measures"] + " |\n| --- | --- | --- |\n")
		for _, m := range gr.gates {
			p := pages[m]
			b.WriteString(fmt.Sprintf("| [`%s`](%s%s/) | %s | %s |\n", m, t["prefix"], m, codeList(p.g.On), escapeCell(capitalize(oneLine(p.g.Describe())))))
		}
		b.WriteString("\n")
	}
	b.WriteString(gateEnd + "\n")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func writeGateSidebar(path string, groups []gateGroup) error {
	type item struct {
		Label string `json:"label"`
		Slug  string `json:"slug"`
	}
	type group struct {
		Label        string            `json:"label"`
		Translations map[string]string `json:"translations"`
		Collapsed    bool              `json:"collapsed"`
		Items        []item            `json:"items"`
	}
	var out []group
	for _, gr := range groups {
		g := group{Label: gr.en, Translations: map[string]string{"pt-BR": gr.pt, "pt": gr.pt}, Collapsed: true}
		for _, m := range gr.gates {
			g.Items = append(g.Items, item{m, "docs/gates/" + m})
		}
		out = append(out, g)
	}
	b, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}

// checkerSources maps each checker name in the gate package's registries to the Go file
// that defines its function, read from the source: the registries are unexported, and the
// file is what links a checker to its spec.
func checkerSources(dir string) (map[string]string, error) {
	fset := token.NewFileSet()
	files, err := filepath.Glob(filepath.Join(dir, "*.go"))
	if err != nil {
		return nil, err
	}
	funcFile := map[string]string{}
	var lits []*ast.CompositeLit
	for _, file := range files {
		if strings.HasSuffix(file, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, file, nil, 0)
		if err != nil {
			return nil, err
		}
		{
			for _, d := range f.Decls {
				switch d := d.(type) {
				case *ast.FuncDecl:
					if d.Recv == nil {
						funcFile[d.Name.Name] = file
					}
				case *ast.GenDecl:
					for _, s := range d.Specs {
						vs, ok := s.(*ast.ValueSpec)
						if !ok {
							continue
						}
						for _, v := range vs.Values {
							if cl, ok := v.(*ast.CompositeLit); ok {
								if mt, ok := cl.Type.(*ast.MapType); ok && isIdent(mt.Key, "string") {
									if _, isFunc := mt.Value.(*ast.FuncType); isFunc {
										lits = append(lits, cl)
									}
								}
							}
						}
					}
				}
			}
		}
	}
	out := map[string]string{}
	for _, cl := range lits {
		for _, e := range cl.Elts {
			kv, ok := e.(*ast.KeyValueExpr)
			if !ok {
				continue
			}
			key, ok := kv.Key.(*ast.BasicLit)
			if !ok {
				continue
			}
			name := strings.Trim(key.Value, `"`)
			if fn := calledFunc(kv.Value); fn != "" {
				if file, ok := funcFile[fn]; ok {
					if _, seen := out[name]; !seen {
						out[name] = file
					}
				}
			}
		}
	}
	return out, nil
}

// calledFunc is the function a registry entry names: the identifier itself, or the first
// function a literal wrapper calls.
func calledFunc(e ast.Expr) string {
	if id, ok := e.(*ast.Ident); ok {
		return id.Name
	}
	name := ""
	ast.Inspect(e, func(n ast.Node) bool {
		if c, ok := n.(*ast.CallExpr); ok && name == "" {
			if id, ok := c.Fun.(*ast.Ident); ok {
				name = id.Name
			}
		}
		return name == ""
	})
	return name
}

func isIdent(e ast.Expr, name string) bool {
	id, ok := e.(*ast.Ident)
	return ok && id.Name == name
}

var relLink = regexp.MustCompile(`\[([^\]]+)\]\((?:\.\.?/)?[^):]+\)`)

// specOverview is the Overview section of a checker's spec, with links into the
// repository turned into their text — they are relative to the spec, not to the site.
func specOverview(path string) string {
	raw, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	var lines []string
	in := false
	for _, l := range strings.Split(string(raw), "\n") {
		if strings.HasPrefix(l, "## ") {
			if in {
				break
			}
			in = strings.TrimSpace(l) == "## Overview"
			continue
		}
		if in {
			if strings.HasPrefix(l, "#") {
				l = "#" + l
			}
			lines = append(lines, l)
		}
	}
	return relLink.ReplaceAllString(strings.TrimSpace(strings.Join(lines, "\n")), "$1")
}

func codeList(xs []string) string {
	if len(xs) == 0 {
		return "—"
	}
	return "`" + strings.Join(xs, "` `") + "`"
}

func yesNo(b bool, t map[string]string) string {
	if b {
		return t["yes"]
	}
	return t["no"]
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
