// Command sitecli writes the site's reference pages from the code itself: one page per
// command, in English and Portuguese, with its description, usage, subcommands, flags and
// the family it belongs to; and one page per gate, from the gate catalog and the spec of
// its checker.
//
// Generated from the command tree, the reference cannot drift from the binary nor leave a
// command out — the hand-grouped pages did both. Only the block between the
// `cli-reference` markers is the generator's: what a person writes around it on a page
// (a guide, an example) is kept.
//
//	go run ./tools/sitecli            # writes site/src/content/docs/{en,pt}/cli/...
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/co2-lab/anchors/cmd/anchors/flow"
	"github.com/co2-lab/anchors/cmd/anchors/governance"
	"github.com/co2-lab/anchors/cmd/anchors/mapcmd"
	"github.com/co2-lab/anchors/cmd/anchors/ops"
	"github.com/co2-lab/anchors/cmd/anchors/quality"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

const (
	startMarker = "<!-- cli-reference:start — generated by `go run ./tools/sitecli` from the CLI; edit the command's help in the code, not this block -->"
	endMarker   = "<!-- cli-reference:end -->"
)

// family is a group of commands close enough that a reader of one needs to know the
// others: every page of the family lists them all, with what tells each apart.
type family struct {
	key     string
	en, pt  string
	members []string
}

var families = []family{
	{"verify", "Confronting the project", "Confronto do projeto", []string{"check", "verify", "coverage", "stale", "impact", "failures"}},
	{"health", "Project health", "Saúde do projeto", []string{"doctor", "audit", "status", "task-status", "compliance", "governs"}},
	{"map", "The map and its signals", "O mapa e seus sinais", []string{"map", "ingest", "test", "mutation", "keep-evidence", "stamp", "recode", "renumber", "generated-paths", "merge-progress"}},
	{"judgment", "Judgment and review", "Julgamento e review", []string{"judge", "review", "suggest"}},
	{"setup", "Setup and artifacts", "Configuração e artefatos", []string{"init", "new", "code", "guide", "docs", "install-hooks", "migrate", "settings", "touch"}},
	{"queue", "The work queue", "A fila de trabalho", []string{"next", "queue", "work", "done", "drop", "reclaim", "deliver", "decided", "discard", "unblock", "escalate", "synthesize", "watch", "flow", "board"}},
	{"freeze", "Freezing the project", "Congelar o projeto", []string{"freeze", "thaw"}},
	{"release", "Changelog and pull requests", "Changelog e pull requests", []string{"changelog", "commit-msg", "pr-body", "backfill-labels", "report"}},
}

// texts are the page's own words in each language; the command's help is the CLI's.
var texts = map[string]map[string]string{
	"en": {"usage": "Usage", "flags": "Flags", "subcommands": "Subcommands", "flag": "Flag", "default": "Default", "what": "What it does", "command": "Command", "family": "family", "familyIntro": "Commands of the same family — what tells each apart:", "dir": "en/cli/commands"},
	"pt": {"usage": "Uso", "flags": "Flags", "subcommands": "Subcomandos", "flag": "Flag", "default": "Padrão", "what": "O que faz", "command": "Comando", "family": "família", "familyIntro": "Comandos da mesma família — o que distingue cada um:", "dir": "pt/cli/comandos"},
}

func main() {
	root := &cobra.Command{Use: "anchors"}
	governance.Register(root)
	mapcmd.Register(root)
	quality.Register(root)
	flow.Register(root)
	ops.Register(root)

	byName := map[string]*cobra.Command{}
	for _, c := range root.Commands() {
		if !c.Hidden && c.Name() != "help" && c.Name() != "completion" {
			byName[c.Name()] = c
		}
	}
	familyOf := map[string]family{}
	for _, f := range families {
		for _, m := range f.members {
			familyOf[m] = f
		}
	}
	var missing []string
	for name := range byName {
		if _, ok := familyOf[name]; !ok {
			missing = append(missing, name)
		}
	}
	if len(missing) > 0 {
		sort.Strings(missing)
		fmt.Fprintf(os.Stderr, "commands with no family — add them to `families`: %s\n", strings.Join(missing, ", "))
		os.Exit(1)
	}

	base := filepath.Join("site", "src", "content", "docs")
	written := 0
	for lang, t := range texts {
		for name, c := range byName {
			path := filepath.Join(base, filepath.FromSlash(t["dir"]), name+".md")
			if err := writePage(path, c, familyOf[name], byName, lang); err != nil {
				fmt.Fprintln(os.Stderr, err)
				os.Exit(1)
			}
			written++
		}
	}
	if err := writeSidebar(filepath.Join("site", "src", "generated", "cli-commands.json"), byName); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %d command page(s) for %d command(s)\n", written, len(byName))
	gates, err := writeGates()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %d gate page(s)\n", gates)
}

// writePage writes the generated block of a command's page, keeping what a person wrote
// outside the markers.
func writePage(path string, c *cobra.Command, f family, byName map[string]*cobra.Command, lang string) error {
	t := texts[lang]
	block := reference(c, f, byName, lang)
	body := ""
	if b, err := os.ReadFile(path); err == nil {
		body = stripFrontmatter(string(b))
		if i := strings.Index(body, startMarker); i >= 0 {
			if j := strings.Index(body, endMarker); j > i {
				body = body[:i] + body[j+len(endMarker):]
			}
		}
		// The separator before a person's text is the generator's too: left in, every run
		// added another.
		body = strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(body), "---"))
	}
	front := fmt.Sprintf("---\ntitle: %q\ndescription: %q\n---\n\n", "anchors "+c.Name(), oneLine(c.Short))
	out := front + block
	if body != "" {
		out += "\n\n---\n\n" + body
	}
	_ = t
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(strings.TrimRight(out, "\n")+"\n"), 0o644)
}

// reference is the generated block: the help, the usage, the flags, the subcommands and
// the family.
func reference(c *cobra.Command, f family, byName map[string]*cobra.Command, lang string) string {
	t := texts[lang]
	var b strings.Builder
	b.WriteString(startMarker + "\n\n")
	b.WriteString(oneLine(c.Short) + ".\n\n")
	if long := strings.TrimSpace(c.Long); long != "" {
		b.WriteString("```text\n" + long + "\n```\n\n")
	}
	writeCommand(&b, c, t, "##")
	var subs []*cobra.Command
	for _, s := range c.Commands() {
		if !s.Hidden && s.Name() != "help" {
			subs = append(subs, s)
		}
	}
	if len(subs) > 0 {
		b.WriteString("## " + t["subcommands"] + "\n\n")
		for _, s := range subs {
			b.WriteString("### `anchors " + c.Name() + " " + s.Name() + "`\n\n")
			b.WriteString(oneLine(s.Short) + ".\n\n")
			if long := strings.TrimSpace(s.Long); long != "" {
				b.WriteString("```text\n" + long + "\n```\n\n")
			}
			writeCommand(&b, s, t, "####")
		}
	}
	b.WriteString("## " + map[string]string{"en": f.en, "pt": f.pt}[lang] + " — " + t["family"] + "\n\n")
	b.WriteString(t["familyIntro"] + "\n\n")
	b.WriteString("| " + t["command"] + " | " + t["what"] + " |\n| --- | --- |\n")
	prefix := "/docs/cli/commands/"
	if lang == "pt" {
		prefix = "/pt/docs/cli/commands/"
	}
	for _, m := range f.members {
		mc, ok := byName[m]
		if !ok {
			continue
		}
		cell := fmt.Sprintf("[`anchors %s`](%s%s/)", m, prefix, m)
		if m == c.Name() {
			cell = "**`anchors " + m + "`**"
		}
		b.WriteString("| " + cell + " | " + escapeCell(oneLine(mc.Short)) + " |\n")
	}
	b.WriteString("\n" + endMarker)
	return b.String()
}

// writeCommand writes a command's usage and its own flags.
func writeCommand(b *strings.Builder, c *cobra.Command, t map[string]string, level string) {
	b.WriteString(level + " " + t["usage"] + "\n\n```bash\n" + strings.TrimSpace(c.UseLine()) + "\n```\n\n")
	var rows []string
	c.LocalFlags().VisitAll(func(f *pflag.Flag) {
		if f.Hidden || f.Name == "help" {
			return
		}
		name := "`--" + f.Name + "`"
		if f.Shorthand != "" {
			name = "`-" + f.Shorthand + "`, " + name
		}
		def := ""
		if f.DefValue != "" && f.DefValue != "false" && f.DefValue != "[]" {
			def = "`" + f.DefValue + "`"
		}
		rows = append(rows, "| "+name+" | "+def+" | "+escapeCell(oneLine(f.Usage))+" |")
	})
	if len(rows) > 0 {
		b.WriteString(level + " " + t["flags"] + "\n\n| " + t["flag"] + " | " + t["default"] + " | " + t["what"] + " |\n| --- | --- | --- |\n")
		b.WriteString(strings.Join(rows, "\n") + "\n\n")
	}
}

// writeSidebar writes the menu's command list, one entry per command in name order, for
// the site config to import.
func writeSidebar(path string, byName map[string]*cobra.Command) error {
	names := make([]string, 0, len(byName))
	for n := range byName {
		names = append(names, n)
	}
	sort.Strings(names)
	var items []map[string]string
	for _, n := range names {
		items = append(items, map[string]string{"label": "anchors " + n, "slug": "docs/cli/commands/" + n})
	}
	b, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}

func stripFrontmatter(s string) string {
	if strings.HasPrefix(s, "---\n") {
		if i := strings.Index(s[4:], "\n---\n"); i >= 0 {
			return s[4+i+5:]
		}
	}
	return s
}

func oneLine(s string) string {
	return strings.TrimSuffix(strings.Join(strings.Fields(s), " "), ".")
}

func escapeCell(s string) string { return strings.ReplaceAll(s, "|", "\\|") }
